use std::fmt;

#[allow(dead_code)]
#[repr(u16)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EMachine {
    None = 0,               // No machine
    M32 = 1,                // AT&T WE 32100
    Sparc = 2,              // SUN SPARC
    I386 = 3,               // Intel 80386
    M68K = 4,               // Motorola m68k family
    M88K = 5,               // Motorola m88k family
    IAMCU = 6,              // Intel MCU
    I860 = 7,               // Intel 80860
    Mips = 8,               // MIPS R3000 big-endian
    S370 = 9,               // IBM System/370
    MipsRs3Le = 10,         // MIPS R3000 little-endian
    Parisc = 15,            // HPPA
    Vpp500 = 17,            // Fujitsu VPP500
    Sparc32Plus = 18,       // Sun's "v8plus"
    I960 = 19,              // Intel 80960
    Ppc = 20,               // PowerPC
    Ppc64 = 21,             // PowerPC 64-bit
    S390 = 22,              // IBM S390
    Spu = 23,               // IBM SPU/SPC
    V800 = 36,              // NEC V800 series
    Fr20 = 37,              // Fujitsu FR20
    Rh32 = 38,              // TRW RH-32
    Rce = 39,               // Motorola RCE
    Arm = 40,               // ARM
    FakeAlpha = 41,         // Digital Alpha
    Sh = 42,                // Hitachi SH
    SparcV9 = 43,           // SPARC v9 64-bit
    Tricore = 44,           // Siemens Tricore
    Arc = 45,               // Argonaut RISC Core
    H8300 = 46,             // Hitachi H8/300
    H8300h = 47,            // Hitachi H8/300H
    H8s = 48,               // Hitachi H8S
    H8500 = 49,             // Hitachi H8/500
    Ia64 = 50,              // Intel Merced
    MipsX = 51,             // Stanford MIPS-X
    Coldfire = 52,          // Motorola Coldfire
    M68hc12 = 53,           // Motorola M68HC12
    Mma = 54,               // Fujitsu MMA Multimedia Accelerator
    Pcp = 55,               // Siemens PCP
    Ncpu = 56,              // Sony nCPU embedded RISC
    Ndr1 = 57,              // Denso NDR1 microprocessor
    Starcore = 58,          // Motorola Start*Core processor
    Me16 = 59,              // Toyota ME16 processor
    St100 = 60,             // STMicroelectronic ST100 processor
    Tinyj = 61,             // Advanced Logic Corp. Tinyj emb.fam
    X8664 = 62,             // AMD x86-64 architecture
    Pdsp = 63,              // Sony DSP Processor
    Pdp10 = 64,             // Digital PDP-10
    Pdp11 = 65,             // Digital PDP-11
    Fx66 = 66,              // Siemens FX66 microcontroller
    St9Plus = 67,           // STMicroelectronics ST9+ 8/16 mc
    St7 = 68,               // STmicroelectronics ST7 8 bit mc
    M68hc16 = 69,           // Motorola MC68HC16 microcontroller
    M68hc11 = 70,           // Motorola MC68HC11 microcontroller
    M68hc08 = 71,           // Motorola MC68HC08 microcontroller
    M68hc05 = 72,           // Motorola MC68HC05 microcontroller
    Svx = 73,               // Silicon Graphics SVx
    St19 = 74,              // STMicroelectronics ST19 8 bit mc
    Vax = 75,               // Digital VAX
    Cris = 76,              // Axis Communications 32-bit emb.proc
    Javelin = 77,           // Infineon Technologies 32-bit emb.proc
    Firepath = 78,          // Element 14 64-bit DSP Processor
    Zsp = 79,               // LSI Logic 16-bit DSP Processor
    Mmix = 80,              // Donald Knuth's educational 64-bit proc
    Huany = 81,             // Harvard University machine-independent object files
    Prism = 82,             // SiTera Prism
    Avr = 83,               // Atmel AVR 8-bit microcontroller
    Fr30 = 84,              // Fujitsu FR30
    D10v = 85,              // Mitsubishi D10V
    D30v = 86,              // Mitsubishi D30V
    V850 = 87,              // NEC v850
    M32r = 88,              // Mitsubishi M32R
    Mn10300 = 89,           // Matsushita MN10300
    Mn10200 = 90,           // Matsushita MN10200
    Pj = 91,                // picoJava
    OpenRisc = 92,          // OpenRISC 32-bit embedded processor
    ArcCompact = 93,        // ARC International ARCompact
    Xtensa = 94,            // Tensilica Xtensa Architecture
    VideoCore = 95,         // Alphamosaic VideoCore
    TmmGpp = 96,            // Thompson Multimedia General Purpose Proc
    Ns32k = 97,             // National Semi. 32000
    Tpc = 98,               // Tenor Network TPC
    Snp1k = 99,             // Trebia SNP 1000
    St200 = 100,            // STMicroelectronics ST200
    Ip2k = 101,             // Ubicom IP2xxx
    Max = 102,              // MAX processor
    Cr = 103,               // National Semi. CompactRISC
    F2mc16 = 104,           // Fujitsu F2MC16
    Msp430 = 105,           // Texas Instruments msp430
    Blackfin = 106,         // Analog Devices Blackfin DSP
    SeC33 = 107,            // Seiko Epson S1C33 family
    Sep = 108,              // Sharp embedded microprocessor
    Arca = 109,             // Arca RISC
    Unicore = 110,          // PKU-Unity & MPRC Peking Uni. mc series
    Excess = 111,           // eXcess configurable cpu
    Dxp = 112,              // Icera Semi. Deep Execution Processor
    AlteraNios2 = 113,      // Altera Nios II
    Crx = 114,              // National Semi. CompactRISC CRX
    Xgate = 115,            // Motorola XGATE
    C166 = 116,             // Infineon C16x/XC16x
    M16c = 117,             // Renesas M16C
    Dspic30f = 118,         // Microchip Technology dsPIC30F
    Ce = 119,               // Freescale Communication Engine RISC
    M32c = 120,             // Renesas M32C
    Tsk3000 = 131,          // Altium TSK3000
    Rs08 = 132,             // Freescale RS08
    Sharc = 133,            // Analog Devices SHARC family
    Ecog2 = 134,            // Cyan Technology eCOG2
    Score7 = 135,           // Sunplus S+core7 RISC
    Dsp24 = 136,            // New Japan Radio (NJR) 24-bit DSP
    VideoCore3 = 137,       // Broadcom VideoCore III
    LatticeMico32 = 138,    // RISC for Lattice FPGA
    SeC17 = 139,            // Seiko Epson C17
    TiC6000 = 140,          // Texas Instruments TMS320C6000 DSP
    TiC2000 = 141,          // Texas Instruments TMS320C2000 DSP
    TiC5500 = 142,          // Texas Instruments TMS320C55x DSP
    TiArp32 = 143,          // Texas Instruments App. Specific RISC
    TiPru = 144,            // Texas Instruments Prog. Realtime Unit
    MmdspPlus = 160,        // STMicroelectronics 64bit VLIW DSP
    CypressM8c = 161,       // Cypress M8C
    R32c = 162,             // Renesas R32C
    Trimedia = 163,         // NXP Semi. TriMedia
    Qdsp6 = 164,            // QUALCOMM DSP6
    Intel8051 = 165,        // Intel 8051 and variants
    Stxp7x = 166,           // STMicroelectronics STxP7x
    Nds32 = 167,            // Andes Tech. compact code emb. RISC
    Ecog1x = 168,           // Cyan Technology eCOG1X
    Maxq30 = 169,           // Dallas Semi. MAXQ30 mc
    Ximo16 = 170,           // New Japan Radio (NJR) 16-bit DSP
    Manik = 171,            // M2000 Reconfigurable RISC
    CrayNv2 = 172,          // Cray NV2 vector architecture
    Rx = 173,               // Renesas RX
    Metag = 174,            // Imagination Tech. META
    McstElbrus = 175,       // MCST Elbrus
    Ecog16 = 176,           // Cyan Technology eCOG16
    Cr16 = 177,             // National Semi. CompactRISC CR16
    Etpu = 178,             // Freescale Extended Time Processing Unit
    Sle9x = 179,            // Infineon Tech. SLE9X
    L10m = 180,             // Intel L10M
    K10m = 181,             // Intel K10M
    Aarch64 = 183,          // ARM AARCH64
    Avr32 = 185,            // Amtel 32-bit microprocessor
    Stm8 = 186,             // STMicroelectronics STM8
    Tile64 = 187,           // Tilera TILE64
    TilePro = 188,          // Tilera TILEPro
    MicroBlaze = 189,       // Xilinx MicroBlaze
    Cuda = 190,             // NVIDIA CUDA
    TileGx = 191,           // Tilera TILE-Gx
    CloudShield = 192,      // CloudShield
    CoreA1st = 193,         // KIPO-KAIST Core-A 1st gen.
    CoreA2nd = 194,         // KIPO-KAIST Core-A 2nd gen.
    Arcv2 = 195,            // Synopsys ARCv2 ISA.
    Open8 = 196,            // Open8 RISC
    Rl78 = 197,             // Renesas RL78
    VideoCore5 = 198,       // Broadcom VideoCore V
    K78kor = 199,           // Renesas 78KOR
    Freescale56800ex = 200, // Freescale 56800EX DSC
    BeyondBa1 = 201,        // Beyond BA1
    BeyondBa2 = 202,        // Beyond BA2
    XmosXcore = 203,        // XMOS xCORE
    MicrochipPic = 204,     // Microchip 8-bit PIC(r)
    IntelGt = 205,          // Intel Graphics Technology
    Km32 = 210,             // KM211 KM32
    Kmx32 = 211,            // KM211 KMX32
    Emx16 = 212,            // KM211 KMX16
    Emx8 = 213,             // KM211 KMX8
    Kvarc = 214,            // KM211 KVARC
    Cdp = 215,              // Paneve CDP
    Coge = 216,             // Cognitive Smart Memory Processor
    Cool = 217,             // Bluechip CoolEngine
    Norc = 218,             // Nanoradio Optimized RISC
    CsrKalimba = 219,       // CSR Kalimba
    Z80 = 220,              // Zilog Z80
    Visium = 221,           // Controls and Data Services VISIUMcore
    Ft32 = 222,             // FTDI Chip FT32
    Moxie = 223,            // Moxie processor
    AmdGpu = 224,           // AMD GPU
    Riscv = 243,            // RISC-V
    Bpf = 247,              // Linux BPF -- in-kernel virtual machine
    Csky = 252,             // C-SKY
    LoongArch = 258,        // LoongArch
    Alpha = 0x9026,         // Old spelling/synonym
}

impl Default for EMachine {
    fn default() -> Self {
        EMachine::None
    }
}

impl fmt::Display for EMachine {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let description = match self {
            EMachine::None => "None",
            EMachine::M32 => "WE32100",
            EMachine::Sparc => "Sparc",
            EMachine::I386 => "Intel 80386",
            EMachine::M68K => "MC68000",
            EMachine::M88K => "MC88000",
            EMachine::IAMCU => "Intel MCU",
            EMachine::I860 => "Intel 80860",
            EMachine::Mips => "MIPS R3000",
            EMachine::S370 => "IBM System/370",
            EMachine::MipsRs3Le => "MIPS R4000 big-endian",
            EMachine::Parisc => "HPPA",
            EMachine::Vpp500 => "Fujitsu VPP500",
            EMachine::Sparc32Plus => "Sparc v8+",
            EMachine::I960 => "Intel 80960",
            EMachine::Ppc => "PowerPC",
            EMachine::Ppc64 => "PowerPC64",
            EMachine::S390 => "IBM S/390",
            EMachine::Spu => "SPU",
            EMachine::V800 => "Renesas V850 (using RH850 ABI)",
            EMachine::Fr20 => "Fujitsu FR20",
            EMachine::Rh32 => "TRW RH32",
            EMachine::Rce => "RCE",
            EMachine::Arm => "ARM",
            EMachine::FakeAlpha => "Digital Alpha (old)",
            EMachine::Sh => "Renesas / SuperH SH",
            EMachine::SparcV9 => "Sparc v9",
            EMachine::Tricore => "Siemens Tricore",
            EMachine::Arc => "ARC",
            EMachine::H8300 => "Renesas H8/300",
            EMachine::H8300h => "Renesas H8/300H",
            EMachine::H8s => "Renesas H8S",
            EMachine::H8500 => "Renesas H8/500",
            EMachine::Ia64 => "Intel IA-64",
            EMachine::MipsX => "Stanford MIPS-X",
            EMachine::Coldfire => "Motorola Coldfire",
            EMachine::M68hc12 => "Motorola MC68HC12 Microcontroller",
            EMachine::Mma => "Fujitsu Multimedia Accelerator",
            EMachine::Pcp => "Siemens PCP",
            EMachine::Ncpu => "Sony nCPU embedded RISC processor",
            EMachine::Ndr1 => "Denso NDR1 microprocessor",
            EMachine::Starcore => "Motorola Star*Core processor",
            EMachine::Me16 => "Toyota ME16 processor",
            EMachine::St100 => "STMicroelectronics ST100 processor",
            EMachine::Tinyj => "Advanced Logic Corp. TinyJ embedded processor",
            EMachine::X8664 => "Advanced Micro Devices X86-64",
            EMachine::Pdsp => "Sony DSP processor",
            EMachine::Pdp10 => "Digital Equipment Corp. PDP-10",
            EMachine::Pdp11 => "Digital Equipment Corp. PDP-11",
            EMachine::Fx66 => "Siemens FX66 microcontroller",
            EMachine::St9Plus => "STMicroelectronics ST9+ 8/16 bit microcontroller",
            EMachine::St7 => "STMicroelectronics ST7 8-bit microcontroller",
            EMachine::M68hc16 => "Motorola MC68HC16 Microcontroller",
            EMachine::M68hc11 => "Motorola MC68HC11 Microcontroller",
            EMachine::M68hc08 => "Motorola MC68HC08 Microcontroller",
            EMachine::M68hc05 => "Motorola MC68HC05 Microcontroller",
            EMachine::Svx => "Silicon Graphics SVx",
            EMachine::St19 => "STMicroelectronics ST19 8-bit microcontroller",
            EMachine::Vax => "Digital VAX",
            EMachine::Cris => "Axis Communications 32-bit embedded processor",
            EMachine::Javelin => "Infineon Technologies 32-bit embedded cpu",
            EMachine::Firepath => "Element 14 64-bit DSP processor",
            EMachine::Zsp => "LSI Logic's 16-bit DSP processor",
            EMachine::Mmix => "Donald Knuth's educational 64-bit processor",
            EMachine::Huany => "Harvard University's machine-independent object format",
            EMachine::Prism => "Vitesse Prism",
            EMachine::Avr => "Atmel AVR 8-bit microcontroller",
            EMachine::Fr30 => "Fujitsu FR30",
            EMachine::D10v => "d10v",
            EMachine::D30v => "d30v",
            EMachine::V850 => "Renesas V850",
            EMachine::M32r => "Renesas M32R (formerly Mitsubishi M32r)",
            EMachine::Mn10300 => "mn10300",
            EMachine::Mn10200 => "mn10200",
            EMachine::Pj => "picoJava",
            EMachine::OpenRisc => "OpenRISC 1000",
            EMachine::ArcCompact => "ARCompact",
            EMachine::Xtensa => "Tensilica Xtensa Processor",
            EMachine::VideoCore => "Alphamosaic VideoCore processor",
            EMachine::TmmGpp => "Thompson Multimedia General Purpose Processor",
            EMachine::Ns32k => "National Semiconductor 32000 series",
            EMachine::Tpc => "Tenor Network TPC processor",
            EMachine::Snp1k => "Trebia SNP 1000 processor",
            EMachine::St200 => "STMicroelectronics ST200 microcontroller",
            EMachine::Ip2k => "Ubicom IP2xxx 8-bit microcontrollers",
            EMachine::Max => "MAX Processor",
            EMachine::Cr => "National Semiconductor CompactRISC",
            EMachine::F2mc16 => "Fujitsu F2MC16",
            EMachine::Msp430 => "Texas Instruments msp430 microcontroller",
            EMachine::Blackfin => "Analog Devices Blackfin",
            EMachine::SeC33 => "S1C33 Family of Seiko Epson processors",
            EMachine::Sep => "Sharp embedded microprocessor",
            EMachine::Arca => "Arca RISC microprocessor",
            EMachine::Unicore => "Unicore",
            EMachine::Excess => "eXcess 16/32/64-bit configurable embedded CPU",
            EMachine::Dxp => "Icera Semiconductor Inc. Deep Execution Processor",
            EMachine::AlteraNios2 => "Altera Nios II",
            EMachine::Crx => "National Semiconductor CRX microprocessor",
            EMachine::Xgate => "Motorola XGATE embedded processor",
            EMachine::C166 => "Infineon Technologies xc16x",
            EMachine::M16c => "Renesas M16C series microprocessors",
            EMachine::Dspic30f => "Microchip Technology dsPIC30F Digital Signal Controller",
            EMachine::Ce => "Freescale Communication Engine RISC core",
            EMachine::M32c => "Renesas M32c",
            EMachine::Tsk3000 => "Altium TSK3000 core",
            EMachine::Rs08 => "Freescale RS08 embedded processor",
            EMachine::Sharc => "Analog Devices SHARC family",
            EMachine::Ecog2 => "Cyan Technology eCOG2 microprocessor",
            EMachine::Score7 => "SUNPLUS S+Core",
            EMachine::Dsp24 => "New Japan Radio (NJR) 24-bit DSP Processor",
            EMachine::VideoCore3 => "Broadcom VideoCore III processor",
            EMachine::LatticeMico32 => "Lattice Mico32",
            EMachine::SeC17 => "Seiko Epson C17 family",
            EMachine::TiC6000 => "Texas Instruments TMS320C6000 DSP family",
            EMachine::TiC2000 => "Texas Instruments TMS320C2000 DSP family",
            EMachine::TiC5500 => "Texas Instruments TMS320C55x DSP family",
            EMachine::TiArp32 => "TI PRU I/O processor",
            EMachine::TiPru => "TI PRU I/O processor",
            EMachine::MmdspPlus => "STMicroelectronics 64bit VLIW Data Signal Processor",
            EMachine::CypressM8c => "Cypress M8C microprocessor",
            EMachine::R32c => "Renesas R32C series microprocessors",
            EMachine::Trimedia => "NXP Semiconductors TriMedia architecture family",
            EMachine::Qdsp6 => "QUALCOMM DSP6 Processor",
            EMachine::Intel8051 => "Intel 8051 and variants",
            EMachine::Stxp7x => "STMicroelectronics STxP7x family",
            EMachine::Nds32 => "Andes Technology compact code size embedded RISC processor family",
            EMachine::Ecog1x => "Cyan Technology eCOG1X family",
            EMachine::Maxq30 => "Dallas Semiconductor MAXQ30 Core microcontrollers",
            EMachine::Ximo16 => "New Japan Radio (NJR) 16-bit DSP Processor",
            EMachine::Manik => "M2000 Reconfigurable RISC Microprocessor",
            EMachine::CrayNv2 => "Cray Inc. NV2 vector architecture",
            EMachine::Rx => "Renesas RX",
            EMachine::Metag => "Imagination Technologies Meta processor architecture",
            EMachine::McstElbrus => "MCST Elbrus general purpose hardware architecture",
            EMachine::Ecog16 => "Cyan Technology eCOG16 family",
            EMachine::Cr16 => "National Semiconductor CompactRISC",
            EMachine::Etpu => "Freescale Extended Time Processing Unit",
            EMachine::Sle9x => "Infineon Technologies SLE9X core",
            EMachine::L10m => "Intel L1OM",
            EMachine::K10m => "Intel K1OM",
            EMachine::Aarch64 => "AArch64",
            EMachine::Avr32 => "Atmel Corporation 32-bit microprocessor",
            EMachine::Stm8 => "STMicroeletronics STM8 8-bit microcontroller",
            EMachine::Tile64 => "Tilera TILE64 multicore architecture family",
            EMachine::TilePro => "Tilera TILEPro multicore architecture family",
            EMachine::MicroBlaze => "Xilinx MicroBlaze",
            EMachine::Cuda => "NVIDIA CUDA architecture",
            EMachine::TileGx => "Tilera TILE-Gx multicore architecture family",
            EMachine::CloudShield => "CloudShield architecture family",
            EMachine::CoreA1st => "KIPO-KAIST Core-A 1st generation processor family",
            EMachine::CoreA2nd => "KIPO-KAIST Core-A 2nd generation processor family",
            EMachine::Arcv2 => "ARCv2",
            EMachine::Open8 => "Open8 8-bit RISC soft processor core",
            EMachine::Rl78 => "Renesas RL78",
            EMachine::VideoCore5 => "Broadcom VideoCore V processor",
            EMachine::K78kor => "Renesas 78K0R",
            EMachine::Freescale56800ex => "Freescale 56800EX Digital Signal Controller (DSC)",
            EMachine::BeyondBa1 => "Beyond BA1 CPU architecture",
            EMachine::BeyondBa2 => "Beyond BA2 CPU architecture",
            EMachine::XmosXcore => "XMOS xCORE processor family",
            EMachine::MicrochipPic => "Microchip 8-bit PIC(r) family",
            EMachine::IntelGt => "Intel Graphics Technology",
            EMachine::Km32 => "KM211 KM32 32-bit processor",
            EMachine::Kmx32 => "KM211 KMX32 32-bit processor",
            EMachine::Emx16 => "KM211 KMX16 16-bit processor",
            EMachine::Emx8 => "KM211 KMX8 8-bit processor",
            EMachine::Kvarc => "KM211 KVARC processor",
            EMachine::Cdp => "Paneve CDP architecture family",
            EMachine::Coge => "Cognitive Smart Memory Processor",
            EMachine::Cool => "Bluechip Systems CoolEngine",
            EMachine::Norc => "Nanoradio Optimized RISC",
            EMachine::CsrKalimba => "CSR Kalimba architecture family",
            EMachine::Z80 => "Zilog Z80",
            EMachine::Visium => "CDS VISIUMcore processor",
            EMachine::Ft32 => "FTDI Chip FT32",
            EMachine::Moxie => "Moxie",
            EMachine::AmdGpu => "AMD GPU",
            EMachine::Riscv => "RISC-V",
            EMachine::Bpf => "Linux BPF",
            EMachine::Csky => "C-SKY",
            EMachine::LoongArch => "LoongArch",
            EMachine::Alpha => "Alpha",
        };
        write!(f, "{}", description)
    }
}
